# Form implementation generated from reading ui file 'E:\Repos\RPL\kasir.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from functools import partial
from datetime import datetime
from PyQt6 import QtCore, QtGui, QtWidgets, QtSql

current_dir = os.path.dirname(os.path.realpath(__file__))

class CineManageModel(object):
	def __init__(self, dbPath, *args, **kwargs):
		super(CineManageModel, self).__init__(*args, **kwargs)
		self.dbPath = dbPath
		self.db = QtSql.QSqlDatabase.addDatabase("QSQLITE")
		self.db.setDatabaseName(self.dbPath)
		if not self.db.open():
			print("CONNECTION FAILED")
			return
		else:
			print("CONNECTED TO DB SUCCESSFULLY")
			
	def fetch(self, SQLQuery):
		data = []
		query = QtSql.QSqlQuery()
		query.prepare(SQLQuery)
		if not query.exec():
			QtCore.qDebug(query.lastError().text())
		if (query.first()):
			row = {query.record().fieldName(i):query.value(query.record().fieldName(i)) for i in range (query.record().count())}
			data.append(row)
			while (query.next()):
				row = {query.record().fieldName(i):query.value(query.record().fieldName(i)) for i in range (query.record().count())}
				data.append(row)
		return data
		
	def fetchBind(self, SQLQuery, placeholders, values):
		data = []
		query = QtSql.QSqlQuery()
		query.prepare(SQLQuery)
		if (len(placeholders) != len(values)):
			return
		for i in range(len(placeholders)):
			query.bindValue(placeholders[i], values[i])
		if not query.exec():
			QtCore.qDebug(query.lastError().text())
		if (query.first()):
			row = {query.record().fieldName(i):query.value(query.record().fieldName(i)) for i in range (query.record().count())}
			data.append(row)
			while (query.next()):
				row = {query.record().fieldName(i):query.value(query.record().fieldName(i)) for i in range (query.record().count())}
				data.append(row)
		else:
			QtCore.qDebug(query.lastError().text())
		return data

	def createTicket(self, seatID, screeningID, studioID):
		query = QtSql.QSqlQuery()
		data = self.fetch("SELECT seatid, studioid, screeningid FROM ticket;")
		if not {"SeatID":seatID, "StudioID":studioID, "ScreeningID":screeningID} in data:
			query.exec("PRAGMA FOREIGN_KEYS=1;")
			query.prepare("INSERT INTO ticket(seatid, studioid, screeningid, orderdatetime) VALUES (:seatID, :studioID, :screeningID, :orderDatetime);")
			query.bindValue(":seatID", seatID)
			query.bindValue(":studioID", studioID)
			query.bindValue(":screeningID", screeningID)
			now = datetime.now()
			query.bindValue(":orderDatetime", now.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3])
			if not query.exec():
				QtCore.qDebug(query.lastError().text())

class Ui_MainWindow(QtWidgets.QMainWindow):
	def setupUi(self):
		super().__init__()
		self.setObjectName("Cashier Menu")
		self.resize(1280, 720)
		self.setMinimumSize(QtCore.QSize(1280, 720))
		self.setMaximumSize(QtCore.QSize(1280, 720))
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("../img/cinemanage.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
		self.setWindowIcon(icon)
		self.model = CineManageModel(os.path.join(current_dir, "cineManage_V3.db"))
		self.centralwidget = QtWidgets.QWidget(self)
		self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
		self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
		self.centralwidget.setStyleSheet("QWidget {\n"
		"    background: #FFDE59\n"
		"}")
		self.centralwidget.setObjectName("centralwidget")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		self.stackedWidget.setGeometry(QtCore.QRect(160, 90, 1120, 630))
		self.stackedWidget.setObjectName("stackedWidget")
		self.orderMenu = QtWidgets.QWidget()
		self.orderMenu.setObjectName("orderMenu")
		self.orderScrollArea = QtWidgets.QScrollArea(self.orderMenu)
		self.orderScrollArea.setGeometry(QtCore.QRect(20, 40, 1071, 581))
		self.orderScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
		self.orderScrollArea.setWidgetResizable(True)
		self.orderScrollArea.setObjectName("orderScrollArea")
		self.stackedWidget.addWidget(self.orderMenu)
		self.screeningMenu = QtWidgets.QWidget()
		self.screeningMenu.setObjectName("screeningMenu")
		self.screeningInfoScrollArea = QtWidgets.QScrollArea(self.screeningMenu)
		self.screeningInfoScrollArea.setGeometry(QtCore.QRect(20, 30, 1071, 581))
		self.screeningInfoScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
		self.screeningInfoScrollArea.setWidgetResizable(True)
		self.screeningInfoScrollArea.setObjectName("screeningInfoScrollArea")
		self.stackedWidget.addWidget(self.screeningMenu)
		self.historyMenu = QtWidgets.QWidget()
		self.historyMenu.setObjectName("historyMenu")
		self.ticketScrollArea = QtWidgets.QScrollArea(self.historyMenu)
		self.ticketScrollArea.setGeometry(QtCore.QRect(270, 30, 821, 581))
		self.ticketScrollArea.setMinimumSize(QtCore.QSize(526, 0))
		self.ticketScrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.ticketScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
		self.ticketScrollArea.setWidgetResizable(True)
		self.ticketScrollArea.setObjectName("ticketScrollArea")
		self.stackedWidget.addWidget(self.historyMenu)
		self.seatSelectMenu = QtWidgets.QWidget()
		self.seatSelectMenu.setObjectName("self.seatSelectMenu")
		self.scrollArea = QtWidgets.QScrollArea(self.seatSelectMenu)
		self.scrollArea.setGeometry(QtCore.QRect(10, 20, 1101, 601))
		self.scrollArea.setWidgetResizable(True)
		self.scrollArea.setObjectName("scrollArea")
		self.stackedWidget.addWidget(self.seatSelectMenu)
		self.successPage = QtWidgets.QWidget()
		self.successPage.setObjectName("successPage")
		self.verticalLayoutWidget = QtWidgets.QWidget(self.successPage)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 210, 391, 191))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.orderSuccessMessage = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.orderSuccessMessage.setMaximumSize(QtCore.QSize(16777215, 200))
		self.orderSuccessMessage.setStyleSheet("QLabel {\n"
		"            width: 89px;\n"
		"            height: 18px;\n"
		"\n"
		"            font-family: \'Roboto\';\n"
		"            font-style: normal;\n"
		"            font-weight: 600;\n"
		"            font-size: 36px;\n"
		"            line-height: 18px;\n"
		"\n"
		"            color: #000000;\n"
		"}")
		self.orderSuccessMessage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.orderSuccessMessage.setObjectName("orderSuccessMessage")
		self.verticalLayout.addWidget(self.orderSuccessMessage)
		self.seeTickets = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.seeTickets.setMinimumSize(QtCore.QSize(150, 60))
		self.seeTickets.setMaximumSize(QtCore.QSize(99999, 60))
		self.seeTickets.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		self.seeTickets.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #32F478;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #25A654 \n"
		"}")
		self.seeTickets.setObjectName("seeTickets")
		self.seeTickets.clicked.connect(self.changeToHistory)
		self.verticalLayout.addWidget(self.seeTickets)
		self.stackedWidget.addWidget(self.successPage)
		self.top_bar = QtWidgets.QFrame(self.centralwidget)
		self.top_bar.setGeometry(QtCore.QRect(0, 0, 1281, 91))
		self.top_bar.setStyleSheet("QFrame {\n"
		"    background: #FFFFFF\n"
		"}")
		self.top_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		self.top_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
		self.top_bar.setObjectName("top_bar")
		self.gridLayout = QtWidgets.QGridLayout(self.top_bar)
		self.gridLayout.setObjectName("gridLayout")
		spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
		self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
		self.profile = QtWidgets.QLabel(self.top_bar)
		self.profile.setMinimumSize(QtCore.QSize(64, 64))
		self.profile.setMaximumSize(QtCore.QSize(64, 64))
		self.profile.setText("")
		self.profile.setPixmap(QtGui.QPixmap("../img/profile.png"))
		self.profile.setObjectName("profile")
		self.gridLayout.addWidget(self.profile, 0, 0, 2, 1)
		spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
		self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
		self.logoutButton = QtWidgets.QPushButton(self.top_bar)
		self.logoutButton.setMinimumSize(QtCore.QSize(150, 40))
		self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		self.logoutButton.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #3084D1;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #0445A9\n"
		"}")
		self.logoutButton.setObjectName("logoutButton")
		self.logoutButton.clicked.connect(self.logout)
		self.gridLayout.addWidget(self.logoutButton, 1, 5, 1, 1)
		self.loggedInLabel = QtWidgets.QLabel(self.top_bar)
		self.loggedInLabel.setStyleSheet("QLabel {\n"
		"            width: 89px;\n"
		"            height: 18px;\n"
		"\n"
		"            font-family: \'Roboto\';\n"
		"            font-style: normal;\n"
		"            font-weight: 600;\n"
		"            font-size: 16px;\n"
		"            line-height: 18px;\n"
		"\n"
		"            color: #000000;\n"
		"            background: #FFFFFF;\n"
		"}")
		self.loggedInLabel.setObjectName("loggedInLabel")
		self.gridLayout.addWidget(self.loggedInLabel, 0, 1, 1, 1)
		self.logo = QtWidgets.QLabel(self.top_bar)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
		self.logo.setSizePolicy(sizePolicy)
		self.logo.setMinimumSize(QtCore.QSize(170, 62))
		self.logo.setMaximumSize(QtCore.QSize(170, 62))
		self.logo.setText("")
		self.logo.setPixmap(QtGui.QPixmap("../img/cmmain.png"))
		self.logo.setScaledContents(True)
		self.logo.setObjectName("logo")
		self.gridLayout.addWidget(self.logo, 0, 3, 2, 1)
		self.cashierLabel = QtWidgets.QLabel(self.top_bar)
		self.cashierLabel.setMinimumSize(QtCore.QSize(0, 40))
		self.cashierLabel.setStyleSheet("QLabel {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 18px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #F04D4D;\n"
		"            border-radius: 20px;\n"
		"}")
		self.cashierLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.cashierLabel.setObjectName("cashierLabel")
		self.gridLayout.addWidget(self.cashierLabel, 1, 1, 1, 1)
		self.frame = QtWidgets.QFrame(self.centralwidget)
		self.frame.setGeometry(QtCore.QRect(0, 90, 160, 630))
		self.frame.setStyleSheet("QFrame {\n"
		"    background: #EAC43F\n"
		"}")
		self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
		self.frame.setObjectName("frame")
		self.orderTicketButton = QtWidgets.QPushButton(self.frame)
		self.orderTicketButton.setGeometry(QtCore.QRect(8, 18, 144, 186))
		self.orderTicketButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		self.orderTicketButton.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #EB8446;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #7C4525\n"
		"}")
		self.orderTicketButton.setObjectName("orderTicketButton")
		self.orderTicketButton.clicked.connect(self.changeToOrder)
		self.screeningInfoButton = QtWidgets.QPushButton(self.frame)
		self.screeningInfoButton.setGeometry(QtCore.QRect(8, 222, 144, 186))
		self.screeningInfoButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		self.screeningInfoButton.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #EB8446;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #7C4525\n"
		"}")
		self.screeningInfoButton.setObjectName("screeningInfoButton")
		self.screeningInfoButton.clicked.connect(self.changeToScreenings)
		self.orderHistoryButton = QtWidgets.QPushButton(self.frame)
		self.orderHistoryButton.setGeometry(QtCore.QRect(8, 426, 144, 186))
		self.orderHistoryButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		self.orderHistoryButton.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #EB8446;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #7C4525\n"
		"}")
		self.orderHistoryButton.setObjectName("orderHistoryButton")
		self.orderHistoryButton.clicked.connect(self.changeToHistory)
		self.displayScreeningInfo()
		self.displayTickets()
		self.orderTickets()
  
		self.setActivePageButton()
  
		self.setCentralWidget(self.centralwidget)

		self.retranslateUi()
		self.stackedWidget.setCurrentIndex(1)
		QtCore.QMetaObject.connectSlotsByName(self)

	def retranslateUi(self):
		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("self", "Cashier Menu"))
		self.orderSuccessMessage.setText(_translate("self", "Order Successful!"))
		self.seeTickets.setText(_translate("self", "See Tickets"))
		self.logoutButton.setText(_translate("self", "Logout"))
		self.loggedInLabel.setText(_translate("self", "You\'re logged in as:"))
		self.cashierLabel.setText(_translate("self", "Cashier"))
		self.orderTicketButton.setText(_translate("self", "Order Tickets\n"
		"Now"))
		self.screeningInfoButton.setText(_translate("self", "Screening\n"
		"Information"))
		self.orderHistoryButton.setText(_translate("self", "Order\n"
		"History"))
  
	def displayScreeningInfo(self):
		data = self.model.fetch("SELECT DISTINCT title, duration, description, poster, name FROM film INNER JOIN screening ON film.title = screening.filmtitle INNER JOIN studio ON screening.studioid=studio.studioid;")
		screeningScrollAreaWidgetContents = QtWidgets.QWidget()
		screeningScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1071, 581))
		screeningScrollAreaWidgetContents.setObjectName("screeningScrollAreaWidgetContents")
		verticalLayout_4 = QtWidgets.QVBoxLayout(screeningScrollAreaWidgetContents)
		verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
		verticalLayout_4.setContentsMargins(0, 2, 0, 2)
		verticalLayout_4.setSpacing(6)
		verticalLayout_4.setObjectName("verticalLayout_4")
		for row in data:
			screeningInfoFrame = QtWidgets.QFrame(screeningScrollAreaWidgetContents)
			screeningInfoFrame.setMinimumSize(QtCore.QSize(1047, 576))
			screeningInfoFrame.setMaximumSize(QtCore.QSize(1047, 576))
			screeningInfoFrame.setStyleSheet("QFrame {background: #FFFFFF;border-radius: 20px }")
			screeningInfoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
			screeningInfoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
			screeningInfoFrame.setObjectName("screeningInfoFrame")
			gridLayout = QtWidgets.QGridLayout(screeningInfoFrame)
			gridLayout.setContentsMargins(15, -1, 15, -1)
			gridLayout.setObjectName("gridLayout_5")
			judulFilm = QtWidgets.QLabel(screeningInfoFrame)
			judulFilm.setMinimumSize(QtCore.QSize(0, 40))
			judulFilm.setMaximumSize(QtCore.QSize(16777215, 40))
			judulFilm.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 600;\n"
			"            font-size: 20px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			judulFilm.setScaledContents(True)
			judulFilm.setObjectName("judulFilm")
			gridLayout.addWidget(judulFilm, 0, 0, 1, 1)
			posterFilm = QtWidgets.QLabel(screeningInfoFrame)
			posterFilm.setMinimumSize(QtCore.QSize(375, 500))
			posterFilm.setMaximumSize(QtCore.QSize(375, 500))
			posterFilm.setScaledContents(True)
			posterFilm.setObjectName("posterFilm")
			gridLayout.addWidget(posterFilm, 1, 0, 1, 1)
			playingNow = QtWidgets.QLabel(screeningInfoFrame)
			playingNow.setMinimumSize(QtCore.QSize(0, 200))
			playingNow.setMaximumSize(QtCore.QSize(16777215, 200))
			playingNow.setStyleSheet("QLabel {font-size: 14px}")
			playingNow.setScaledContents(True)
			playingNow.setWordWrap(True)
			playingNow.setObjectName("playingOrNot")
			gridLayout.addWidget(playingNow, 2, 1, 1, 1)
			durasiFilm = QtWidgets.QLabel(screeningInfoFrame)
			durasiFilm.setMinimumSize(QtCore.QSize(0, 40))
			durasiFilm.setMaximumSize(QtCore.QSize(16777215, 40))
			durasiFilm.setStyleSheet("QLabel {font-size: 18px}")
			durasiFilm.setScaledContents(True)
			durasiFilm.setObjectName("durasiFilm")
			gridLayout.addWidget(durasiFilm, 0, 1, 1, 1)
			getTickets = QtWidgets.QPushButton(screeningInfoFrame)
			getTickets.setMinimumSize(QtCore.QSize(150, 80))
			getTickets.setMaximumSize(QtCore.QSize(150, 80))
			getTickets.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			getTickets.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #32F478;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #25A654 \n"
			"}")
			getTickets.setObjectName("getTickets")
			gridLayout.addWidget(getTickets, 2, 2, 1, 1)
			deskripsiFilm = QtWidgets.QLabel(screeningInfoFrame)
			deskripsiFilm.setMinimumSize(QtCore.QSize(0, 250))
			deskripsiFilm.setMaximumSize(QtCore.QSize(16777215, 500))
			deskripsiFilm.setStyleSheet("QLabel {font-size: 14px}")
			deskripsiFilm.setScaledContents(True)
			deskripsiFilm.setWordWrap(True)
			deskripsiFilm.setObjectName("deskripsiFilm")
			gridLayout.addWidget(deskripsiFilm, 1, 1, 1, 2)
   
			judulFilm.setText(row.get("Title"))
			durasiFilm.setText("Duration: " + str(row.get("Duration")) + " Minute(s)")
			deskripsiFilm.setText(row.get("Description"))
			playingNow.setText("NOW PLAYING")
			getTickets.setText("GET TICKETS")
			getTickets.clicked.connect(self.changeToOrder)
			if len(row.get("Poster")) == 0 or not os.path.exists(row.get("Poster")):
				posterFilm.setPixmap(QtGui.QPixmap("../img/sample_poster.png"))
			else:
				posterFilm.setPixmap(QtGui.QPixmap(row.get("Poster")))

			verticalLayout_4.addWidget(screeningInfoFrame)
		self.screeningInfoScrollArea.setWidget(screeningScrollAreaWidgetContents)
	
	def orderTickets(self):
		data = self.model.fetch("SELECT screeningid, filmtitle, date, starttime, endtime, studio.name, studio.capacity FROM screening INNER JOIN studio ON screening.studioid = studio.studioid ORDER BY DATE(date) DESC;")
		ahead = []
		orderScrollAreaWidgetContents_6 = QtWidgets.QWidget()
		orderScrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 1071, 581))
		orderScrollAreaWidgetContents_6.setObjectName("orderScrollAreaWidgetContents_6")
		verticalLayout_5 = QtWidgets.QVBoxLayout(orderScrollAreaWidgetContents_6)
		verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
		verticalLayout_5.setContentsMargins(-1, -1, -1, 11)
		verticalLayout_5.setObjectName("verticalLayout_5")
		for row in data:
			if row in ahead:
				continue
			orderFrame = QtWidgets.QFrame(orderScrollAreaWidgetContents_6)
			orderFrame.setMinimumSize(QtCore.QSize(1036, 275))
			orderFrame.setMaximumSize(QtCore.QSize(1036, 275))
			orderFrame.setStyleSheet("QFrame {background: #FFFFFF; border-radius: 20px }")
			orderFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
			orderFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
			orderFrame.setObjectName("orderFrame")
			gridLayout = QtWidgets.QGridLayout(orderFrame)
			gridLayout.setObjectName("gridLayout_7")
			judulFilm = QtWidgets.QLabel(orderFrame)
			judulFilm.setMaximumSize(QtCore.QSize(16777215, 16777215))
			judulFilm.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 600;\n"
			"            font-size: 20px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			judulFilm.setScaledContents(True)
			judulFilm.setWordWrap(True)
			judulFilm.setObjectName("judulFilmOrderPage")
			gridLayout.addWidget(judulFilm, 0, 0, 1, 2)
			jadwal1 = QtWidgets.QPushButton(orderFrame)
			jadwal1.setMinimumSize(QtCore.QSize(198, 80))
			jadwal1.setMaximumSize(QtCore.QSize(198, 80))
			jadwal1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			jadwal1.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #0445A9\n"
			"}")
			jadwal1.setObjectName("jadwal1"+ "-" + str(row.get("ScreeningID")))
			gridLayout.addWidget(jadwal1, 1, 0, 1, 1)
			jadwal2 = QtWidgets.QPushButton(orderFrame)
			jadwal2.setMinimumSize(QtCore.QSize(197, 80))
			jadwal2.setMaximumSize(QtCore.QSize(197, 80))
			jadwal2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			jadwal2.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #0445A9\n"
			"}")
			jadwal2.setObjectName("jadwal2"+ "-" + str(row.get("ScreeningID")))
			gridLayout.addWidget(jadwal2, 1, 1, 1, 1)
			studioName = QtWidgets.QLabel(orderFrame)
			studioName.setMaximumSize(QtCore.QSize(16777215, 16777215))
			studioName.setMinimumSize(QtCore.QSize(197, 16777215))
			studioName.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 600;\n"
			"            font-size: 20px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			studioName.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
			studioName.setObjectName("studioOrderPage")
			gridLayout.addWidget(studioName, 0, 4, 1, 1)
			jadwal3 = QtWidgets.QPushButton(orderFrame)
			jadwal3.setMinimumSize(QtCore.QSize(197, 80))
			jadwal3.setMaximumSize(QtCore.QSize(197, 80))
			jadwal3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			jadwal3.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #0445A9\n"
			"}")
			jadwal3.setObjectName("jadwal3"+ "-" + str(row.get("ScreeningID")))
			gridLayout.addWidget(jadwal3, 1, 2, 1, 1)
			jadwal4 = QtWidgets.QPushButton(orderFrame)
			jadwal4.setMinimumSize(QtCore.QSize(197, 80))
			jadwal4.setMaximumSize(QtCore.QSize(197, 80))
			jadwal4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			jadwal4.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #0445A9\n"
			"}")
			jadwal4.setObjectName("jadwal4"+ "-" + str(row.get("ScreeningID")))
			gridLayout.addWidget(jadwal4, 1, 3, 1, 1)
			jadwal5 = QtWidgets.QPushButton(orderFrame)
			jadwal5.setMinimumSize(QtCore.QSize(197, 80))
			jadwal5.setMaximumSize(QtCore.QSize(197, 80))
			jadwal5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			jadwal5.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 20px;\n"
			"        }\n"
			"\n"
			"QPushButton:pressed {\n"
			"    background: #0445A9\n"
			"}")
			jadwal5.setObjectName("jadwal5"+ "-" + str(row.get("ScreeningID")))
			gridLayout.addWidget(jadwal5, 1, 4, 1, 1)
			tanggalPenayangan = QtWidgets.QLabel(orderFrame)
			tanggalPenayangan.setMaximumSize(QtCore.QSize(16777215, 16777215))
			tanggalPenayangan.setMinimumSize(QtCore.QSize(197, 16777215))
			tanggalPenayangan.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 400;\n"
			"            font-size: 18px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			tanggalPenayangan.setScaledContents(True)
			tanggalPenayangan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
			tanggalPenayangan.setObjectName("tanggalPenayangan")
			gridLayout.addWidget(tanggalPenayangan, 0, 2, 1, 1)

			judulFilm.setText(row.get("FilmTitle"))
			studioName.setText(row.get("Name"))
			tanggalPenayangan.setText(row.get("Date"))
   
			jadwal1.setText(row.get("StartTime") + " - " + row.get("EndTime"))
			jadwal1.clicked.connect(partial(self.selectSeat, row.get("ScreeningID")))
   
			j = (jadwal2, jadwal3, jadwal4, jadwal5)

			for i in range(len(data)):
				if i <= data.index(row):
					continue
				
				if (data[i].get("StudioID") == row.get("StudioID")) and (data[i].get("FilmTitle") == row.get("FilmTitle")) and (data[i].get("Date") == row.get("Date")):
					for id in range(4):
						if len(j[id].text()) == 0:
							j[id].setText(data[i].get("StartTime") + " - " + data[i].get("EndTime"))
							j[id].clicked.connect(partial(self.selectSeat, data[i].get("ScreeningID")))
							break
					ahead.append(data[i])

			for jadwal in j:
				if len(jadwal.text()) == 0:	
					gridLayout.removeWidget(jadwal)
			for i in range(5):
				gridLayout.setColumnMinimumWidth(i, 197)

			verticalLayout_5.addWidget(orderFrame)

		self.orderScrollArea.setWidget(orderScrollAreaWidgetContents_6)

	def displayTickets(self):
		data = self.model.fetch("SELECT ticket.screeningid, screening.studioid, seatid, filmtitle, name, date, starttime, endtime, orderdatetime FROM ticket INNER JOIN screening ON ticket.screeningid=screening.screeningid INNER JOIN studio ON screening.studioid=studio.studioid ORDER BY DATETIME(orderdatetime, 'auto') DESC;")
		ticketScrollAreaWidgetContents = QtWidgets.QWidget()
		ticketScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 821, 581))
		ticketScrollAreaWidgetContents.setObjectName("ticketScrollAreaWidgetContents_7")
		verticalLayout_6 = QtWidgets.QVBoxLayout(ticketScrollAreaWidgetContents)
		verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
		verticalLayout_6.setObjectName("verticalLayout_6")
		for row in data:
			ticketHistoryFrame = QtWidgets.QFrame(ticketScrollAreaWidgetContents)
			ticketHistoryFrame.setMinimumSize(QtCore.QSize(500, 350))
			ticketHistoryFrame.setMaximumSize(QtCore.QSize(500, 350))
			ticketHistoryFrame.setStyleSheet("QFrame {background: #FFFFFF;border-radius:20px }")
			ticketHistoryFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
			ticketHistoryFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
			ticketHistoryFrame.setObjectName("ticketHistoryFrame")
			gridLayout = QtWidgets.QGridLayout(ticketHistoryFrame)
			gridLayout.setObjectName("gridLayout_8")
			jamPenayangan = QtWidgets.QLabel(ticketHistoryFrame)
			jamPenayangan.setStyleSheet("QLabel {font-size: 14px}")
			jamPenayangan.setScaledContents(True)
			jamPenayangan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
			jamPenayangan.setObjectName("jamPenayangan")
			gridLayout.addWidget(jamPenayangan, 3, 1, 1, 1)
			barisKursi = QtWidgets.QLabel(ticketHistoryFrame)
			barisKursi.setStyleSheet("QLabel {font-size: 14px}")
			barisKursi.setScaledContents(True)
			barisKursi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
			barisKursi.setObjectName("barisKursi")
			gridLayout.addWidget(barisKursi, 3, 2, 1, 1)
			tanggalPenayangan = QtWidgets.QLabel(ticketHistoryFrame)
			tanggalPenayangan.setStyleSheet("QLabel {font-size: 14px}")
			tanggalPenayangan.setScaledContents(True)
			tanggalPenayangan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
			tanggalPenayangan.setObjectName("tanggalPenayangan")
			gridLayout.addWidget(tanggalPenayangan, 3, 0, 1, 1)
			nomorKursi = QtWidgets.QLabel(ticketHistoryFrame)
			nomorKursi.setStyleSheet("QLabel {font-size: 14px}")
			nomorKursi.setScaledContents(True)
			nomorKursi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
			nomorKursi.setObjectName("nomorKursi")
			gridLayout.addWidget(nomorKursi, 3, 3, 1, 1)
			idTiket = QtWidgets.QLabel(ticketHistoryFrame)
			idTiket.setStyleSheet("QLabel {font-size: 14px}")
			idTiket.setScaledContents(True)
			idTiket.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
			idTiket.setObjectName("idTiket")
			gridLayout.addWidget(idTiket, 4, 1, 1, 3)
			judulFilmTiket = QtWidgets.QLabel(ticketHistoryFrame)
			judulFilmTiket.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 600;\n"
			"            font-size: 18px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			judulFilmTiket.setScaledContents(True)
			judulFilmTiket.setWordWrap(True)
			judulFilmTiket.setObjectName("judulFilmTicketPage")
			gridLayout.addWidget(judulFilmTiket, 0, 0, 1, 2)
			studioPenayangan = QtWidgets.QLabel(ticketHistoryFrame)
			studioPenayangan.setStyleSheet("QLabel {\n"
			"            width: 89px;\n"
			"            height: 18px;\n"
			"\n"
			"            font-family: \'Roboto\';\n"
			"            font-style: normal;\n"
			"            font-weight: 600;\n"
			"            font-size: 18px;\n"
			"            line-height: 18px;\n"
			"\n"
			"            color: #000000;\n"
			"            background: #FFFFFF;\n"
			"}")
			studioPenayangan.setScaledContents(True)
			studioPenayangan.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
			studioPenayangan.setObjectName("studioTicketPage")
			gridLayout.addWidget(studioPenayangan, 0, 2, 1, 2)
   
			judulFilmTiket.setText(row.get("FilmTitle"))
			studioPenayangan.setText(row.get("Name"))
			tanggalPenayangan.setText("Date:\n" + row.get("Date"))
			jamPenayangan.setText("Time:\n" + row.get("StartTime") + " - " + row.get("EndTime"))
			barisKursi.setText("Seat Row:\n" + row.get("SeatID")[0])
			nomorKursi.setText("Seat No.:\n" + row.get("SeatID")[1:])
			idTiket.setText("Ticket ID: " + str(row.get("ScreeningID")) + str(row.get("StudioID")) + "-" + row.get("SeatID") + "-" + row.get("OrderDatetime"))
   
			verticalLayout_6.addWidget(ticketHistoryFrame)
		self.ticketScrollArea.setWidget(ticketScrollAreaWidgetContents)
   
	def changeToScreenings(self):
		self.displayScreeningInfo()
		self.stackedWidget.setCurrentWidget(self.screeningMenu)
		self.setActivePageButton()
  
	def changeToOrder(self):
		self.orderTickets()
		self.stackedWidget.setCurrentWidget(self.orderMenu)
		self.setActivePageButton()
  
	def changeToHistory(self):
		self.displayTickets()
		self.stackedWidget.setCurrentWidget(self.historyMenu)
		self.setActivePageButton()
  
	def selectSeat(self, screeningID):
		self.stackedWidget.setCurrentWidget(self.seatSelectMenu)
		data = self.model.fetchBind("SELECT screening.screeningid, filmtitle, studio.studioid, name, capacity, date, starttime, endtime, seatid FROM screening INNER JOIN ticket ON screening.screeningid = ticket.screeningid INNER JOIN studio ON screening.studioid = studio.studioid WHERE ticket.screeningid=:screeningID;", [":screeningID"], [screeningID])
		initial = False
		if len(data) == 0:
			data = self.model.fetchBind("SELECT screeningid, filmtitle, studio.studioid, name, capacity, date, starttime, endtime FROM screening INNER JOIN studio ON screening.studioid = studio.studioid WHERE screeningid=:screeningID;", [":screeningID"], [screeningID])
			initial = True
		
		orders = set([])
		
		scrollAreaWidgetContents = QtWidgets.QWidget()
		scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1099, 599))
		scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		verticalLayout_2 = QtWidgets.QVBoxLayout(scrollAreaWidgetContents)
		verticalLayout_2.setObjectName("verticalLayout_2")
		horizontalLayout_2 = QtWidgets.QHBoxLayout()
		horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
		horizontalLayout_2.setSpacing(5)
		horizontalLayout_2.setObjectName("horizontalLayout_2")
		backButton = QtWidgets.QPushButton(scrollAreaWidgetContents)
		backButton.setMinimumSize(QtCore.QSize(150, 40))
		backButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
		backButton.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #3084D1;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #0445A9\n"
		"}")
		backButton.setText("Back")
		backButton.setObjectName("backButton")
		backButton.clicked.connect(self.changeToOrder)
		horizontalLayout_2.addWidget(backButton)
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
		horizontalLayout_2.addItem(spacerItem)
		judulANDstudioANDtanggal = QtWidgets.QLabel(scrollAreaWidgetContents)
		judulANDstudioANDtanggal.setStyleSheet("QLabel {\n"
		"            width: 89px;\n"
		"            height: 18px;\n"
		"\n"
		"            font-family: \'Roboto\';\n"
		"            font-style: normal;\n"
		"            font-weight: 600;\n"
		"            font-size: 16px;\n"
		"            line-height: 18px;\n"
		"\n"
		"            color: #000000;\n"
		"}")
		judulANDstudioANDtanggal.setScaledContents(True)
		judulANDstudioANDtanggal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		judulANDstudioANDtanggal.setWordWrap(True)
		judulANDstudioANDtanggal.setText(data[0].get("FilmTitle")+"\n"+data[0].get("Name")+"\n"+data[0].get("Date")+" "+data[0].get("StartTime")+" - "+data[0].get("EndTime"))
		judulANDstudioANDtanggal.setObjectName("judulnStudionTanggal")
		horizontalLayout_2.addWidget(judulANDstudioANDtanggal)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
		horizontalLayout_2.addItem(spacerItem1)
		bookSeatsButton = QtWidgets.QPushButton(scrollAreaWidgetContents)
		bookSeatsButton.setMinimumSize(QtCore.QSize(200, 40))
		bookSeatsButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
		bookSeatsButton.setStyleSheet("QPushButton {\n"
									"            font-family: \'Inter\';\n"
									"            font-style: normal;\n"
									"            font-weight: 700;\n"
									"            font-size: 20px;\n"
									"            line-height: 87.69%;\n"
									"\n"
									"            color: #FFFFFF;\n"
									"            background: #C1C1C1;\n"
									"            border-radius: 20px;\n"
									"        }\n")
		bookSeatsButton.setDisabled(True)
		bookSeatsButton.setText("Book Seat(s)")
		bookSeatsButton.setObjectName("bookSeatsButton")
		horizontalLayout_2.addWidget(bookSeatsButton)
		verticalLayout_2.addLayout(horizontalLayout_2)
		
		for i in range(int(data[0].get("Capacity")/25)):
			horizontalLayout = QtWidgets.QHBoxLayout()
			horizontalLayout.setSpacing(5)
			horizontalLayout.setObjectName("horizontalLayout")
			seat_1 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_1.setMinimumSize(QtCore.QSize(35, 35))
			seat_1.setMaximumSize(QtCore.QSize(35, 35))
			seat_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_1.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_1.setText("")
			seat_1.setCheckable(True)
			seat_1.setObjectName("seat_1")
			horizontalLayout.addWidget(seat_1)
			seat_2 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_2.setMinimumSize(QtCore.QSize(35, 35))
			seat_2.setMaximumSize(QtCore.QSize(35, 35))
			seat_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_2.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_2.setText("")
			seat_2.setCheckable(True)
			seat_2.setObjectName("seat_2")
			horizontalLayout.addWidget(seat_2)
			seat_3 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_3.setMinimumSize(QtCore.QSize(35, 35))
			seat_3.setMaximumSize(QtCore.QSize(35, 35))
			seat_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_3.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_3.setText("")
			seat_3.setCheckable(True)
			seat_3.setObjectName("seat_3")
			horizontalLayout.addWidget(seat_3)
			seat_4 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_4.setMinimumSize(QtCore.QSize(35, 35))
			seat_4.setMaximumSize(QtCore.QSize(35, 35))
			seat_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_4.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_4.setText("")
			seat_4.setCheckable(True)
			seat_4.setObjectName("seat_4")
			horizontalLayout.addWidget(seat_4)
			seat_5 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_5.setMinimumSize(QtCore.QSize(35, 35))
			seat_5.setMaximumSize(QtCore.QSize(35, 35))
			seat_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_5.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_5.setText("")
			seat_5.setCheckable(True)
			seat_5.setObjectName("seat_5")
			horizontalLayout.addWidget(seat_5)
			seat_6 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_6.setMinimumSize(QtCore.QSize(35, 35))
			seat_6.setMaximumSize(QtCore.QSize(35, 35))
			seat_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_6.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_6.setText("")
			seat_6.setCheckable(True)
			seat_6.setObjectName("seat_6")
			horizontalLayout.addWidget(seat_6)
			spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
			horizontalLayout.addItem(spacerItem2)
			seat_7 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_7.setMinimumSize(QtCore.QSize(35, 35))
			seat_7.setMaximumSize(QtCore.QSize(35, 35))
			seat_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_7.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_7.setText("")
			seat_7.setCheckable(True)
			seat_7.setObjectName("seat_7")
			horizontalLayout.addWidget(seat_7)
			seat_8 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_8.setMinimumSize(QtCore.QSize(35, 35))
			seat_8.setMaximumSize(QtCore.QSize(35, 35))
			seat_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_8.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_8.setText("")
			seat_8.setCheckable(True)
			seat_8.setObjectName("seat_8")
			horizontalLayout.addWidget(seat_8)
			seat_9 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_9.setMinimumSize(QtCore.QSize(35, 35))
			seat_9.setMaximumSize(QtCore.QSize(35, 35))
			seat_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_9.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_9.setText("")
			seat_9.setCheckable(True)
			seat_9.setObjectName("seat_9")
			horizontalLayout.addWidget(seat_9)
			seat_10 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_10.setMinimumSize(QtCore.QSize(35, 35))
			seat_10.setMaximumSize(QtCore.QSize(35, 35))
			seat_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_10.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_10.setText("")
			seat_10.setCheckable(True)
			seat_10.setObjectName("seat_10")
			horizontalLayout.addWidget(seat_10)
			seat_11 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_11.setMinimumSize(QtCore.QSize(35, 35))
			seat_11.setMaximumSize(QtCore.QSize(35, 35))
			seat_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_11.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_11.setText("")
			seat_11.setCheckable(True)
			seat_11.setObjectName("seat_11")
			horizontalLayout.addWidget(seat_11)
			seat_12 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_12.setMinimumSize(QtCore.QSize(35, 35))
			seat_12.setMaximumSize(QtCore.QSize(35, 35))
			seat_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_12.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_12.setText("")
			seat_12.setCheckable(True)
			seat_12.setObjectName("seat_12")
			horizontalLayout.addWidget(seat_12)
			seat_13 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_13.setMinimumSize(QtCore.QSize(35, 35))
			seat_13.setMaximumSize(QtCore.QSize(35, 35))
			seat_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_13.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_13.setText("")
			seat_13.setCheckable(True)
			seat_13.setObjectName("seat_13")
			horizontalLayout.addWidget(seat_13)
			seat_14 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_14.setMinimumSize(QtCore.QSize(35, 35))
			seat_14.setMaximumSize(QtCore.QSize(35, 35))
			seat_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_14.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_14.setText("")
			seat_14.setCheckable(True)
			seat_14.setObjectName("seat_14")
			horizontalLayout.addWidget(seat_14)
			seat_15 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_15.setMinimumSize(QtCore.QSize(35, 35))
			seat_15.setMaximumSize(QtCore.QSize(35, 35))
			seat_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_15.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_15.setText("")
			seat_15.setCheckable(True)
			seat_15.setObjectName("seat_15")
			horizontalLayout.addWidget(seat_15)
			seat_16 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_16.setMinimumSize(QtCore.QSize(35, 35))
			seat_16.setMaximumSize(QtCore.QSize(35, 35))
			seat_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_16.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_16.setText("")
			seat_16.setCheckable(True)
			seat_16.setObjectName("seat_16")
			horizontalLayout.addWidget(seat_16)
			seat_17 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_17.setMinimumSize(QtCore.QSize(35, 35))
			seat_17.setMaximumSize(QtCore.QSize(35, 35))
			seat_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_17.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_17.setText("")
			seat_17.setCheckable(True)
			seat_17.setObjectName("seat_17")
			horizontalLayout.addWidget(seat_17)
			seat_18 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_18.setMinimumSize(QtCore.QSize(35, 35))
			seat_18.setMaximumSize(QtCore.QSize(35, 35))
			seat_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_18.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_18.setText("")
			seat_18.setCheckable(True)
			seat_18.setObjectName("seat_18")
			horizontalLayout.addWidget(seat_18)
			seat_19 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_19.setMinimumSize(QtCore.QSize(35, 35))
			seat_19.setMaximumSize(QtCore.QSize(35, 35))
			seat_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_19.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_19.setText("")
			seat_19.setCheckable(True)
			seat_19.setObjectName("seat_19")
			horizontalLayout.addWidget(seat_19)
			spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
			horizontalLayout.addItem(spacerItem3)
			seat_20 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_20.setMinimumSize(QtCore.QSize(35, 35))
			seat_20.setMaximumSize(QtCore.QSize(35, 35))
			seat_20.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_20.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_20.setText("")
			seat_20.setCheckable(True)
			seat_20.setObjectName("seat_20")
			horizontalLayout.addWidget(seat_20)
			seat_21 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_21.setMinimumSize(QtCore.QSize(35, 35))
			seat_21.setMaximumSize(QtCore.QSize(35, 35))
			seat_21.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_21.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_21.setText("")
			seat_21.setCheckable(True)
			seat_21.setObjectName("seat_21")
			horizontalLayout.addWidget(seat_21)
			seat_22 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_22.setMinimumSize(QtCore.QSize(35, 35))
			seat_22.setMaximumSize(QtCore.QSize(35, 35))
			seat_22.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_22.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_22.setText("")
			seat_22.setCheckable(True)
			seat_22.setObjectName("seat_22")
			horizontalLayout.addWidget(seat_22)
			seat_23 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_23.setMinimumSize(QtCore.QSize(35, 35))
			seat_23.setMaximumSize(QtCore.QSize(35, 35))
			seat_23.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_23.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_23.setText("")
			seat_23.setCheckable(True)
			seat_23.setObjectName("seat_23")
			horizontalLayout.addWidget(seat_23)
			seat_24 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_24.setMinimumSize(QtCore.QSize(35, 35))
			seat_24.setMaximumSize(QtCore.QSize(35, 35))
			seat_24.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_24.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_24.setText("")
			seat_24.setCheckable(True)
			seat_24.setObjectName("seat_24")
			horizontalLayout.addWidget(seat_24)
			seat_25 = QtWidgets.QPushButton(scrollAreaWidgetContents)
			seat_25.setMinimumSize(QtCore.QSize(35, 35))
			seat_25.setMaximumSize(QtCore.QSize(35, 35))
			seat_25.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			seat_25.setStyleSheet("QPushButton {\n"
			"            font-family: \'Inter\';\n"
			"            font-style: normal;\n"
			"            font-weight: 700;\n"
			"            font-size: 20px;\n"
			"            line-height: 87.69%;\n"
			"\n"
			"            color: #FFFFFF;\n"
			"            background: #3084D1;\n"
			"            border-radius: 10px;\n"
			"        }\n"
			"\n"
			"QPushButton:on {\n"
			"    background: #0445A9\n"
			"}")
			seat_25.setText("")
			seat_25.setCheckable(True)
			seat_25.setObjectName("seat_25")
			horizontalLayout.addWidget(seat_25)
			seats = (seat_1, seat_2, seat_3, seat_4, seat_5, seat_6, seat_7, seat_8, seat_9, seat_10, seat_11, seat_12, seat_13, seat_14, seat_15, 
                 seat_16, seat_17, seat_18, seat_19, seat_20, seat_21, seat_22, seat_23, seat_24, seat_25)
            
			for x in range(25):
				name = str(f"{chr(65+i)}{x+1}")
				seats[x].setText(name)
				seats[x].setObjectName(name)
				if (not initial):
					for row in data:
						if seats[x].objectName() == row.get("SeatID"):
							seats[x].setStyleSheet("QPushButton {\n"
													"            font-family: \'Inter\';\n"
													"            font-style: normal;\n"
													"            font-weight: 700;\n"
													"            font-size: 20px;\n"
													"            line-height: 87.69%;\n"
													"\n"
													"            color: #FFFFFF;\n"
													"            background: #EB311F;\n"
													"            border-radius: 10px;\n"
													"        }\n"
													"\n"
													"QPushButton:on {\n"
													"    background: #0445A9\n"
													"}")
							seats[x].setCheckable(False)
							seats[x].setDisabled(True)
							seats[x].setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
							break
						else:
							seats[x].clicked.connect(partial(self.book, seats[x], seats[x].objectName(), data[0].get("ScreeningID"), orders, bookSeatsButton))
				else:
					seats[x].clicked.connect(partial(self.book, seats[x], seats[x].objectName(), data[0].get("ScreeningID"), orders, bookSeatsButton))

			verticalLayout_2.addLayout(horizontalLayout)
			
  
		screen = QtWidgets.QPushButton(scrollAreaWidgetContents)
		screen.setMinimumSize(QtCore.QSize(150, 30))
		screen.setMaximumSize(QtCore.QSize(16777215, 30))
		screen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
		screen.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #000000;\n"
		"            border-radius: 0px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #0445A9\n"
		"}")
		screen.setObjectName("screen")
		screen.setText("Screen")
		verticalLayout_2.addWidget(screen)
		self.scrollArea.setWidget(scrollAreaWidgetContents)
	
	def book(self, seat, seatID, screeningID, orderlist, cfrmBtn):
		if seat.isChecked():
			if not ((seatID, screeningID) in orderlist):
				orderlist.add((seatID, screeningID))
		else:
			if (seatID, screeningID) in orderlist:
				orderlist.remove((seatID, screeningID))

		if len(orderlist) != 0:
			cfrmBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
			cfrmBtn.setStyleSheet("QPushButton {\n"
										"            font-family: \'Inter\';\n"
										"            font-style: normal;\n"
										"            font-weight: 700;\n"
										"            font-size: 20px;\n"
										"            line-height: 87.69%;\n"
										"\n"
										"            color: #FFFFFF;\n"
										"            background: #EB8446;\n"
										"            border-radius: 20px;\n"
										"        }\n"
										"\n"
										"QPushButton:pressed {\n"
										"    background: #7C4525\n"
										"}")
			cfrmBtn.setDisabled(False)
			cfrmBtn.clicked.connect(partial(self.completeBook, orderlist))
		
		else:
			cfrmBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
			cfrmBtn.setStyleSheet("QPushButton {\n"
										"            font-family: \'Inter\';\n"
										"            font-style: normal;\n"
										"            font-weight: 700;\n"
										"            font-size: 20px;\n"
										"            line-height: 87.69%;\n"
										"\n"
										"            color: #FFFFFF;\n"
										"            background: #C1C1C1;\n"
										"            border-radius: 20px;\n"
										"        }\n")
			cfrmBtn.setDisabled(True)
			
		print(orderlist)
  
	def completeBook(self, orderlist):
		data = self.model.fetchBind("SELECT studioid FROM screening WHERE screeningid=:screeningID", [":screeningID"], [list(orderlist)[0][1]])
		studioID = data[0].get("StudioID")
		for order in list(orderlist):
			self.model.createTicket(order[0], order[1], studioID)
		self.stackedWidget.setCurrentWidget(self.successPage)
  
	def logout(self):
		self.close()
		os.system('python main.py')
  
	def setActivePageButton(self):
		if self.stackedWidget.currentWidget() == self.orderMenu:
			button = self.orderTicketButton
			others = [self.orderHistoryButton, self.screeningInfoButton]
   
		elif self.stackedWidget.currentWidget() == self.historyMenu:
			button = self.orderHistoryButton
			others = [self.orderTicketButton, self.screeningInfoButton]
   
		elif self.stackedWidget.currentWidget() == self.screeningMenu:
			button = self.screeningInfoButton
			others = [self.orderTicketButton, self.orderHistoryButton]

		button.setStyleSheet("QPushButton {\n"
	"            font-family: \'Inter\';\n"
	"            font-style: normal;\n"
	"            font-weight: 700;\n"
	"            font-size: 20px;\n"
	"            line-height: 87.69%;\n"
	"\n"
	"            color: #FFFFFF;\n"
	"            background: #7C4525;\n"
	"            border-radius: 20px;\n"
	"        }")
		button.setDisabled(True)
		for button in others:
			button.setStyleSheet("QPushButton {\n"
		"            font-family: \'Inter\';\n"
		"            font-style: normal;\n"
		"            font-weight: 700;\n"
		"            font-size: 20px;\n"
		"            line-height: 87.69%;\n"
		"\n"
		"            color: #FFFFFF;\n"
		"            background: #EB8446;\n"
		"            border-radius: 20px;\n"
		"        }\n"
		"\n"
		"QPushButton:pressed {\n"
		"    background: #7C4525\n"
		"}")
			button.setDisabled(False)

if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)
 
	ui = Ui_MainWindow()
	ui.setupUi()

	ui.stackedWidget.setCurrentWidget(ui.orderMenu)
	ui.show()
	sys.exit(app.exec())
