# Form implementation generated from reading ui file 'E:\Repos\RPL\kasir.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.next = None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/cinemanage.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background: #FFDE59\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 90, 1120, 630))
        self.stackedWidget.setObjectName("stackedWidget")
        self.orderMenu = QtWidgets.QWidget()
        self.orderMenu.setObjectName("orderMenu")
        self.orderScrollArea = QtWidgets.QScrollArea(self.orderMenu)
        self.orderScrollArea.setGeometry(QtCore.QRect(20, 40, 1071, 581))
        self.orderScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.orderScrollArea.setWidgetResizable(True)
        self.orderScrollArea.setObjectName("orderScrollArea")
        self.orderScrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.orderScrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 1071, 581))
        self.orderScrollAreaWidgetContents_6.setObjectName("orderScrollAreaWidgetContents_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.orderScrollAreaWidgetContents_6)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.orderFrame = QtWidgets.QFrame(self.orderScrollAreaWidgetContents_6)
        self.orderFrame.setMinimumSize(QtCore.QSize(1047, 275))
        self.orderFrame.setMaximumSize(QtCore.QSize(1047, 275))
        self.orderFrame.setStyleSheet("QFrame {background: #FFFFFF; border-radius: 20px }")
        self.orderFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.orderFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.orderFrame.setObjectName("orderFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.orderFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.judulFilmOrderPage = QtWidgets.QLabel(self.orderFrame)
        self.judulFilmOrderPage.setMaximumSize(QtCore.QSize(753, 16777215))
        self.judulFilmOrderPage.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 20px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.judulFilmOrderPage.setScaledContents(True)
        self.judulFilmOrderPage.setObjectName("judulFilmOrderPage")
        self.gridLayout_7.addWidget(self.judulFilmOrderPage, 0, 0, 1, 1)
        self.jadwal1 = QtWidgets.QPushButton(self.orderFrame)
        self.jadwal1.setMinimumSize(QtCore.QSize(150, 80))
        self.jadwal1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.jadwal1.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.jadwal1.setObjectName("jadwal1")
        self.gridLayout_7.addWidget(self.jadwal1, 1, 0, 1, 1)
        self.jadwal2 = QtWidgets.QPushButton(self.orderFrame)
        self.jadwal2.setMinimumSize(QtCore.QSize(150, 80))
        self.jadwal2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.jadwal2.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.jadwal2.setObjectName("jadwal2")
        self.gridLayout_7.addWidget(self.jadwal2, 1, 1, 1, 1)
        self.studioOrderPage = QtWidgets.QLabel(self.orderFrame)
        self.studioOrderPage.setMaximumSize(QtCore.QSize(250, 16777215))
        self.studioOrderPage.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 20px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.studioOrderPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.studioOrderPage.setObjectName("studioOrderPage")
        self.gridLayout_7.addWidget(self.studioOrderPage, 0, 3, 1, 1)
        self.jadwal4 = QtWidgets.QPushButton(self.orderFrame)
        self.jadwal4.setMinimumSize(QtCore.QSize(150, 80))
        self.jadwal4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.jadwal4.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.jadwal4.setObjectName("jadwal4")
        self.gridLayout_7.addWidget(self.jadwal4, 1, 3, 1, 1)
        self.jadwal3 = QtWidgets.QPushButton(self.orderFrame)
        self.jadwal3.setMinimumSize(QtCore.QSize(150, 80))
        self.jadwal3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.jadwal3.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.jadwal3.setObjectName("jadwal3")
        self.gridLayout_7.addWidget(self.jadwal3, 1, 2, 1, 1)
        self.tanggalPenayangan = QtWidgets.QLabel(self.orderFrame)
        self.tanggalPenayangan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tanggalPenayangan.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 400;\n"
"            font-size: 18px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.tanggalPenayangan.setScaledContents(True)
        self.tanggalPenayangan.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tanggalPenayangan.setObjectName("tanggalPenayangan")
        self.gridLayout_7.addWidget(self.tanggalPenayangan, 0, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.orderFrame)
        self.orderScrollArea.setWidget(self.orderScrollAreaWidgetContents_6)
        self.stackedWidget.addWidget(self.orderMenu)
        self.screeningMenu = QtWidgets.QWidget()
        self.screeningMenu.setObjectName("screeningMenu")
        self.screeningInfoScrollArea = QtWidgets.QScrollArea(self.screeningMenu)
        self.screeningInfoScrollArea.setGeometry(QtCore.QRect(20, 30, 1071, 581))
        self.screeningInfoScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.screeningInfoScrollArea.setWidgetResizable(True)
        self.screeningInfoScrollArea.setObjectName("screeningInfoScrollArea")
        self.screeningScrollAreaWidgetContents = QtWidgets.QWidget()
        self.screeningScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1071, 581))
        self.screeningScrollAreaWidgetContents.setObjectName("screeningScrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.screeningScrollAreaWidgetContents)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(0, 2, 0, 2)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.screeningInfoFrame = QtWidgets.QFrame(self.screeningScrollAreaWidgetContents)
        self.screeningInfoFrame.setMinimumSize(QtCore.QSize(1047, 576))
        self.screeningInfoFrame.setMaximumSize(QtCore.QSize(1047, 576))
        self.screeningInfoFrame.setStyleSheet("QFrame {background: #FFFFFF;border-radius: 20px }")
        self.screeningInfoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.screeningInfoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.screeningInfoFrame.setObjectName("screeningInfoFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.screeningInfoFrame)
        self.gridLayout_5.setContentsMargins(15, -1, 15, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.judulFilm = QtWidgets.QLabel(self.screeningInfoFrame)
        self.judulFilm.setMinimumSize(QtCore.QSize(0, 40))
        self.judulFilm.setMaximumSize(QtCore.QSize(16777215, 40))
        self.judulFilm.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 20px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.judulFilm.setScaledContents(True)
        self.judulFilm.setObjectName("judulFilm")
        self.gridLayout_5.addWidget(self.judulFilm, 0, 0, 1, 1)
        self.posterFilm = QtWidgets.QLabel(self.screeningInfoFrame)
        self.posterFilm.setMinimumSize(QtCore.QSize(375, 500))
        self.posterFilm.setMaximumSize(QtCore.QSize(375, 500))
        self.posterFilm.setScaledContents(True)
        self.posterFilm.setObjectName("posterFilm")
        self.gridLayout_5.addWidget(self.posterFilm, 1, 0, 1, 1)
        self.playingOrNot = QtWidgets.QLabel(self.screeningInfoFrame)
        self.playingOrNot.setMinimumSize(QtCore.QSize(0, 200))
        self.playingOrNot.setMaximumSize(QtCore.QSize(16777215, 200))
        self.playingOrNot.setStyleSheet("QLabel {font-size: 14px}")
        self.playingOrNot.setScaledContents(True)
        self.playingOrNot.setWordWrap(True)
        self.playingOrNot.setObjectName("playingOrNot")
        self.gridLayout_5.addWidget(self.playingOrNot, 2, 1, 1, 1)
        self.durasiFilm = QtWidgets.QLabel(self.screeningInfoFrame)
        self.durasiFilm.setMinimumSize(QtCore.QSize(0, 40))
        self.durasiFilm.setMaximumSize(QtCore.QSize(16777215, 40))
        self.durasiFilm.setStyleSheet("QLabel {font-size: 18px}")
        self.durasiFilm.setScaledContents(True)
        self.durasiFilm.setObjectName("durasiFilm")
        self.gridLayout_5.addWidget(self.durasiFilm, 0, 1, 1, 1)
        self.getTickets = QtWidgets.QPushButton(self.screeningInfoFrame)
        self.getTickets.setMinimumSize(QtCore.QSize(150, 80))
        self.getTickets.setMaximumSize(QtCore.QSize(150, 80))
        self.getTickets.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.getTickets.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #32F478;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #25A654 \n"
"}")
        self.getTickets.setObjectName("getTickets")
        self.gridLayout_5.addWidget(self.getTickets, 2, 2, 1, 1)
        self.deskripsiFilm = QtWidgets.QLabel(self.screeningInfoFrame)
        self.deskripsiFilm.setMinimumSize(QtCore.QSize(0, 250))
        self.deskripsiFilm.setMaximumSize(QtCore.QSize(16777215, 500))
        self.deskripsiFilm.setStyleSheet("QLabel {font-size: 14px}")
        self.deskripsiFilm.setScaledContents(True)
        self.deskripsiFilm.setWordWrap(True)
        self.deskripsiFilm.setObjectName("deskripsiFilm")
        self.gridLayout_5.addWidget(self.deskripsiFilm, 1, 1, 1, 2)
        self.verticalLayout_4.addWidget(self.screeningInfoFrame)
        self.screeningInfoScrollArea.setWidget(self.screeningScrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.screeningMenu)
        self.historyMenu = QtWidgets.QWidget()
        self.historyMenu.setObjectName("historyMenu")
        self.ticketScrollArea = QtWidgets.QScrollArea(self.historyMenu)
        self.ticketScrollArea.setGeometry(QtCore.QRect(270, 30, 821, 581))
        self.ticketScrollArea.setMinimumSize(QtCore.QSize(526, 0))
        self.ticketScrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ticketScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ticketScrollArea.setWidgetResizable(True)
        self.ticketScrollArea.setObjectName("ticketScrollArea")
        self.ticketScrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.ticketScrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 821, 581))
        self.ticketScrollAreaWidgetContents_7.setObjectName("ticketScrollAreaWidgetContents_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ticketScrollAreaWidgetContents_7)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ticketHistoryFrame = QtWidgets.QFrame(self.ticketScrollAreaWidgetContents_7)
        self.ticketHistoryFrame.setMinimumSize(QtCore.QSize(500, 350))
        self.ticketHistoryFrame.setMaximumSize(QtCore.QSize(500, 350))
        self.ticketHistoryFrame.setStyleSheet("QFrame {background: #FFFFFF;border-radius:20px }")
        self.ticketHistoryFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ticketHistoryFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ticketHistoryFrame.setObjectName("ticketHistoryFrame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ticketHistoryFrame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.jamTiket = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.jamTiket.setStyleSheet("QLabel {font-size: 14px}")
        self.jamTiket.setScaledContents(True)
        self.jamTiket.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.jamTiket.setObjectName("jamTiket")
        self.gridLayout_8.addWidget(self.jamTiket, 3, 1, 1, 1)
        self.barisKursi = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.barisKursi.setStyleSheet("QLabel {font-size: 14px}")
        self.barisKursi.setScaledContents(True)
        self.barisKursi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.barisKursi.setObjectName("barisKursi")
        self.gridLayout_8.addWidget(self.barisKursi, 3, 2, 1, 1)
        self.tanggalTiket = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.tanggalTiket.setStyleSheet("QLabel {font-size: 14px}")
        self.tanggalTiket.setScaledContents(True)
        self.tanggalTiket.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tanggalTiket.setObjectName("tanggalTiket")
        self.gridLayout_8.addWidget(self.tanggalTiket, 3, 0, 1, 1)
        self.nomorKursi = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.nomorKursi.setStyleSheet("QLabel {font-size: 14px}")
        self.nomorKursi.setScaledContents(True)
        self.nomorKursi.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nomorKursi.setObjectName("nomorKursi")
        self.gridLayout_8.addWidget(self.nomorKursi, 3, 3, 1, 1)
        self.idTiket = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.idTiket.setStyleSheet("QLabel {font-size: 14px}")
        self.idTiket.setScaledContents(True)
        self.idTiket.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.idTiket.setObjectName("idTiket")
        self.gridLayout_8.addWidget(self.idTiket, 4, 1, 1, 3)
        self.judulFilmTicketPage = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.judulFilmTicketPage.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 18px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.judulFilmTicketPage.setScaledContents(True)
        self.judulFilmTicketPage.setObjectName("judulFilmTicketPage")
        self.gridLayout_8.addWidget(self.judulFilmTicketPage, 0, 0, 1, 2)
        self.studioTicketPage = QtWidgets.QLabel(self.ticketHistoryFrame)
        self.studioTicketPage.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 18px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.studioTicketPage.setScaledContents(True)
        self.studioTicketPage.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.studioTicketPage.setObjectName("studioTicketPage")
        self.gridLayout_8.addWidget(self.studioTicketPage, 0, 2, 1, 2)
        self.verticalLayout_6.addWidget(self.ticketHistoryFrame)
        self.ticketScrollArea.setWidget(self.ticketScrollAreaWidgetContents_7)
        self.stackedWidget.addWidget(self.historyMenu)
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1281, 91))
        self.top_bar.setStyleSheet("QFrame {\n"
"    background: #FFFFFF\n"
"}")
        self.top_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.top_bar.setObjectName("top_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.top_bar)
        self.gridLayout.setObjectName("gridLayout")
        self.profile = QtWidgets.QLabel(self.top_bar)
        self.profile.setMinimumSize(QtCore.QSize(64, 64))
        self.profile.setMaximumSize(QtCore.QSize(64, 64))
        self.profile.setText("")
        self.profile.setPixmap(QtGui.QPixmap("../img/profile.png"))
        self.profile.setObjectName("profile")
        self.gridLayout.addWidget(self.profile, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.logo = QtWidgets.QLabel(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(170, 62))
        self.logo.setMaximumSize(QtCore.QSize(170, 62))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../img/cmmain.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 3, 2, 1)
        self.logoutButton = QtWidgets.QPushButton(self.top_bar)
        self.logoutButton.setMinimumSize(QtCore.QSize(150, 40))
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logoutButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.logoutButton.setObjectName("logoutButton")
        self.gridLayout.addWidget(self.logoutButton, 1, 5, 1, 1)
        self.loggedInLabel = QtWidgets.QLabel(self.top_bar)
        self.loggedInLabel.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 16px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.loggedInLabel.setObjectName("loggedInLabel")
        self.gridLayout.addWidget(self.loggedInLabel, 0, 1, 1, 1)
        self.cashierLabel = QtWidgets.QLabel(self.top_bar)
        self.cashierLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.cashierLabel.setStyleSheet("QLabel {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 18px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #F04D4D;\n"
"            border-radius: 20px;\n"
"}")
        self.cashierLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cashierLabel.setObjectName("cashierLabel")
        self.gridLayout.addWidget(self.cashierLabel, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 160, 630))
        self.frame.setStyleSheet("QFrame {\n"
"    background: #EAC43F\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.orderTicketButton = QtWidgets.QPushButton(self.frame)
        self.orderTicketButton.setGeometry(QtCore.QRect(8, 18, 144, 186))
        self.orderTicketButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.orderTicketButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #EB8446;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #7C4525\n"
"}")
        self.orderTicketButton.setObjectName("orderTicketButton")
        self.screeningInfoButton = QtWidgets.QPushButton(self.frame)
        self.screeningInfoButton.setGeometry(QtCore.QRect(8, 222, 144, 186))
        self.screeningInfoButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.screeningInfoButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #EB8446;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #7C4525\n"
"}")
        self.screeningInfoButton.setObjectName("screeningInfoButton")
        self.orderHistoryButton = QtWidgets.QPushButton(self.frame)
        self.orderHistoryButton.setGeometry(QtCore.QRect(8, 426, 144, 186))
        self.orderHistoryButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.orderHistoryButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #EB8446;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #7C4525\n"
"}")
        self.orderHistoryButton.setObjectName("orderHistoryButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.judulFilmOrderPage.setText(_translate("MainWindow", "<JudulFilm>"))
        self.jadwal1.setText(_translate("MainWindow", "<Jadwal 1>"))
        self.jadwal2.setText(_translate("MainWindow", "<Jadwal 2>"))
        self.studioOrderPage.setText(_translate("MainWindow", "<NamaStudio>"))
        self.jadwal4.setText(_translate("MainWindow", "<Jadwal 4>"))
        self.jadwal3.setText(_translate("MainWindow", "<Jadwal 3>"))
        self.tanggalPenayangan.setText(_translate("MainWindow", "<Date>"))
        self.judulFilm.setText(_translate("MainWindow", "<JudulFilm>"))
        self.posterFilm.setText(_translate("MainWindow", "<Poster>"))
        self.playingOrNot.setText(_translate("MainWindow", "<PlayingOrNot>"))
        self.durasiFilm.setText(_translate("MainWindow", "<Durasi>"))
        self.getTickets.setText(_translate("MainWindow", "Get Tickets"))
        self.deskripsiFilm.setText(_translate("MainWindow", "<Deskripsi>"))
        self.jamTiket.setText(_translate("MainWindow", "<Time>"))
        self.barisKursi.setText(_translate("MainWindow", "<SeatRow>"))
        self.tanggalTiket.setText(_translate("MainWindow", "<Date>"))
        self.nomorKursi.setText(_translate("MainWindow", "<SeatNumber>"))
        self.idTiket.setText(_translate("MainWindow", "<TicketID>"))
        self.judulFilmTicketPage.setText(_translate("MainWindow", "<JudulFilm>"))
        self.studioTicketPage.setText(_translate("MainWindow", "<Studio #>"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.loggedInLabel.setText(_translate("MainWindow", "You\'re logged in as:"))
        self.cashierLabel.setText(_translate("MainWindow", "Cashier"))
        self.orderTicketButton.setText(_translate("MainWindow", "Order Ticket\n"
"Now"))
        self.screeningInfoButton.setText(_translate("MainWindow", "Screening\n"
"Information"))
        self.orderHistoryButton.setText(_translate("MainWindow", "Order\n"
"History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
