# Form implementation generated from reading ui file 'E:\Repos\RPL\selectSeat.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        Form.setStyleSheet("QWidget {\n"
"    background: #FFDE59\n"
"}")
        self.top_bar = QtWidgets.QFrame(Form)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1281, 91))
        self.top_bar.setStyleSheet("QFrame {\n"
"    background: #FFFFFF\n"
"}")
        self.top_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.top_bar.setObjectName("top_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.top_bar)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.top_bar)
        self.label.setMinimumSize(QtCore.QSize(64, 64))
        self.label.setMaximumSize(QtCore.QSize(64, 64))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\Repos\\RPL\\Tubes_remote/TugasBesarIF3152_K02_G06/img/profile.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(170, 62))
        self.label_4.setMaximumSize(QtCore.QSize(170, 62))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\Repos\\RPL\\Tubes_remote/TugasBesarIF3152_K02_G06/img/cmmain.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 2, 1)
        self.button_4 = QtWidgets.QPushButton(self.top_bar)
        self.button_4.setMinimumSize(QtCore.QSize(150, 40))
        self.button_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_4.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.top_bar)
        self.label_2.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 16px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"            background: #FFFFFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.top_bar)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setStyleSheet("QLabel {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 18px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #F04D4D;\n"
"            border-radius: 20px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(9, 99, 1261, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.selectPage = QtWidgets.QWidget()
        self.selectPage.setObjectName("selectPage")
        self.scrollArea = QtWidgets.QScrollArea(self.selectPage)
        self.scrollArea.setGeometry(QtCore.QRect(-10, 20, 1261, 581))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1259, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.backButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.backButton.setMinimumSize(QtCore.QSize(150, 40))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #3084D1;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0445A9\n"
"}")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_8.addWidget(self.backButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.bookSeatsButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bookSeatsButton.setMinimumSize(QtCore.QSize(200, 40))
        self.bookSeatsButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bookSeatsButton.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #EB8446;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #7C4525\n"
"}")
        self.bookSeatsButton.setObjectName("bookSeatsButton")
        self.horizontalLayout_8.addWidget(self.bookSeatsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        
        self.stackedWidget.addWidget(self.selectPage)
        self.successPage = QtWidgets.QWidget()
        self.successPage.setObjectName("successPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.successPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.bookSeatsButton_2 = QtWidgets.QPushButton(self.successPage)
        self.bookSeatsButton_2.setMinimumSize(QtCore.QSize(200, 40))
        self.bookSeatsButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bookSeatsButton_2.setStyleSheet("QPushButton {\n"
"            font-family: \'Inter\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 20px;\n"
"            line-height: 87.69%;\n"
"\n"
"            color: #FFFFFF;\n"
"            background: #EB8446;\n"
"            border-radius: 20px;\n"
"        }\n"
"\n"
"QPushButton:pressed {\n"
"    background: #7C4525\n"
"}")
        self.bookSeatsButton_2.setObjectName("bookSeatsButton_2")
        self.gridLayout_2.addWidget(self.bookSeatsButton_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.successPage)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_5.setStyleSheet("QLabel {\n"
"            width: 89px;\n"
"            height: 18px;\n"
"\n"
"            font-family: \'Roboto\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 36px;\n"
"            line-height: 18px;\n"
"\n"
"            color: #000000;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.successPage)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_4.setText(_translate("Form", "Logout"))
        self.label_2.setText(_translate("Form", "You\'re logged in as:"))
        self.label_3.setText(_translate("Form", "Cashier"))
        self.backButton.setText(_translate("Form", "Back"))
        self.bookSeatsButton.setText(_translate("Form", "Book Seat(s)"))
        self.bookSeatsButton_2.setText(_translate("Form", "See Tickets"))
        self.label_5.setText(_translate("Form", "Order Successful!"))
